version: "2"

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose
  settings:
    govet:
      enable:
        - shadow
      disable:
        - slog

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
    - text: "variable name '.*' is too short"
      linters:
        - revive

  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt