run:
  timeout: 5m
  # 新版本中使用 skip-dirs 依然有效（配置文件中尚未弃用）
  # 但更现代的做法是在 issues 层面进行排除
  skip-dirs:
    - vendor
    - third_party

linters:
  disable-all: false
  enable:
    - errcheck # 检查未处理的错误（建议保留）
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - lll          # 关闭行太长的检查
    - gocyclo      # 关闭代码复杂度检查
    - dupl         # 关闭代码重复检查
    - typecheck    # 如果泛型报错太严重，可以暂时关闭
    - revive       # 很多关于注释的琐碎规则都在这里，关掉它

issues:
  exclude-rules:
    - path: _test\.go # 测试文件不进行严格检查
      linters:
        - errcheck
    - text: "excuse me" # 排除包含特定文字的报错