app-id: macbook-pro.local
enable-wrrp: false
help: false
level: debug
listen: :8080
management-url: http://lattice.run
save: true
server-url: ""
show-system-log: false
signaling-url: nats://signaling.alattice.io:4222
token: fIJr6BpT2captanz
turnserver-url: stun.alattice.io:3478
version: false
lrp-url: 81.68.109.143:6266
