// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: signaling/grpc/signaling/signaling.proto

package signaling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MessageDirectOfferType       MessageType = 0
	MessageType_MessageDirectOfferAnswerType MessageType = 1
	MessageType_MessageRelayOfferType        MessageType = 2
	MessageType_MessageRelayAnswerType       MessageType = 3
	MessageType_MessageForwardType           MessageType = 4
	MessageType_MessageHeartBeatType         MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MessageDirectOfferType",
		1: "MessageDirectOfferAnswerType",
		2: "MessageRelayOfferType",
		3: "MessageRelayAnswerType",
		4: "MessageForwardType",
		5: "MessageHeartBeatType",
	}
	MessageType_value = map[string]int32{
		"MessageDirectOfferType":       0,
		"MessageDirectOfferAnswerType": 1,
		"MessageRelayOfferType":        2,
		"MessageRelayAnswerType":       3,
		"MessageForwardType":           4,
		"MessageHeartBeatType":         5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_signaling_grpc_signaling_signaling_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_signaling_grpc_signaling_signaling_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_signaling_grpc_signaling_signaling_proto_rawDescGZIP(), []int{0}
}

// SignalingMessage is dynamic message for kind to request and response
type SignalingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Encrypt       int32                  `protobuf:"varint,4,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	MsgType       MessageType            `protobuf:"varint,6,opt,name=msgType,proto3,enum=MessageType" json:"msgType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalingMessage) Reset() {
	*x = SignalingMessage{}
	mi := &file_signaling_grpc_signaling_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalingMessage) ProtoMessage() {}

func (x *SignalingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_grpc_signaling_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalingMessage.ProtoReflect.Descriptor instead.
func (*SignalingMessage) Descriptor() ([]byte, []int) {
	return file_signaling_grpc_signaling_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *SignalingMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SignalingMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SignalingMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SignalingMessage) GetEncrypt() int32 {
	if x != nil {
		return x.Encrypt
	}
	return 0
}

func (x *SignalingMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SignalingMessage) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_MessageDirectOfferType
}

var File_signaling_grpc_signaling_signaling_proto protoreflect.FileDescriptor

var file_signaling_grpc_signaling_signaling_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x10, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x07, 0x6d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x2a, 0xb4, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12,
	0x20, 0x0a, 0x1c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x4f, 0x66, 0x66, 0x65, 0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x10,
	0x01, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x6c, 0x61,
	0x79, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x10, 0x04,
	0x12, 0x18, 0x0a, 0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x10, 0x05, 0x32, 0x4b, 0x0a, 0x10, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37,
	0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x11,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x6c, 0x69, 0x6e, 0x6b, 0x61,
	0x6e, 0x79, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_signaling_grpc_signaling_signaling_proto_rawDescOnce sync.Once
	file_signaling_grpc_signaling_signaling_proto_rawDescData = file_signaling_grpc_signaling_signaling_proto_rawDesc
)

func file_signaling_grpc_signaling_signaling_proto_rawDescGZIP() []byte {
	file_signaling_grpc_signaling_signaling_proto_rawDescOnce.Do(func() {
		file_signaling_grpc_signaling_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(file_signaling_grpc_signaling_signaling_proto_rawDescData)
	})
	return file_signaling_grpc_signaling_signaling_proto_rawDescData
}

var file_signaling_grpc_signaling_signaling_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signaling_grpc_signaling_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_signaling_grpc_signaling_signaling_proto_goTypes = []any{
	(MessageType)(0),         // 0: MessageType
	(*SignalingMessage)(nil), // 1: SignalingMessage
}
var file_signaling_grpc_signaling_signaling_proto_depIdxs = []int32{
	0, // 0: SignalingMessage.msgType:type_name -> MessageType
	1, // 1: SignalingService.Signaling:input_type -> SignalingMessage
	1, // 2: SignalingService.Signaling:output_type -> SignalingMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_signaling_grpc_signaling_signaling_proto_init() }
func file_signaling_grpc_signaling_signaling_proto_init() {
	if File_signaling_grpc_signaling_signaling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_signaling_grpc_signaling_signaling_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaling_grpc_signaling_signaling_proto_goTypes,
		DependencyIndexes: file_signaling_grpc_signaling_signaling_proto_depIdxs,
		EnumInfos:         file_signaling_grpc_signaling_signaling_proto_enumTypes,
		MessageInfos:      file_signaling_grpc_signaling_signaling_proto_msgTypes,
	}.Build()
	File_signaling_grpc_signaling_signaling_proto = out.File
	file_signaling_grpc_signaling_signaling_proto_rawDesc = nil
	file_signaling_grpc_signaling_signaling_proto_goTypes = nil
	file_signaling_grpc_signaling_signaling_proto_depIdxs = nil
}
