# cluster-role-template.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lattice-editor
rules:
  - apiGroups: ["alattice.io"]
    resources: ["latticepeers", "latticenetworks"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["alattice.io"]
    resources: ["latticepolicies", "latticeenrollmenttokens"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]