resources:
  - manager.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - service_account.yaml
  - lattice-role-binding.yaml
  - lattice-ip-pool.yaml
  - lattice-web.yaml

# 推荐做法 (Kustomize v5+)
labels:
  - pairs:
      app.kubernetes.io/name: lattice-manager
      app.kubernetes.io/part-of: lattice
    includeSelectors: true
    includeTemplates: true  # 同时也给 Pod Template 打上标签

images:
  - name: ghcr.io/alatticeio/lattice-web
    newTag: dev  # 在这里指定你的特定版本（Tag）