apiVersion: alattice.io/v1alpha1
kind: LatticeGlobalIPPool
metadata:
  labels:
    app.kubernetes.io/name: lattice-controller
    app.kubernetes.io/managed-by: kustomize
  name: ip-pool
spec:
  cidr: 10.0.0.0/8
  subnetMask: 24
