// Copyright 2026 The Lattice Authors, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package infra

import (
	"context"
	"encoding/binary"
	"fmt"
	"net"
	"net/netip"

	"golang.zx2c4.com/wireguard/conn"
	"golang.zx2c4.com/wireguard/wgctrl/wgtypes"
)

// WRRP protocol constants.
const (
	WrrpForward uint8 = 0x02 // Data forwarding
)

type Wrrp interface {
	ReceiveFunc() conn.ReceiveFunc
	Send(ctx context.Context, remoteId uint64, wrrpType uint8, data []byte) error
	Connect() error
	RemoteAddr() net.Addr
	Close() error
}

var (
	_ conn.Endpoint = (*WRRPEndpoint)(nil)
)

func IDFromPublicKey(pubKey string) ([32]byte, error) {
	key, err := wgtypes.ParseKey(pubKey)
	if err != nil {
		return [32]byte{}, err
	}
	return key, nil
}

// wrrpFakePrefix is the fixed /96 ULA prefix used to encode WRRP remote IDs
// as fake IPv6 addresses for display in wg show.
//
// "fd77:7272:7000::" — "fd" (ULA) + "wr"(7772) + "rp"(7000).
// The lower 8 bytes carry the 64-bit RemoteId in big-endian order.
var wrrpFakePrefix = [8]byte{0xfd, 0x77, 0x72, 0x72, 0x70, 0x00, 0x00, 0x00}

const WrrpFakePort = 51820

// WrrpFakeAddrPort encodes a WRRP RemoteId as a fake IPv6 AddrPort.
// The resulting address looks like fd77:7272:7000:0:<hi>:<hi>:<lo>:<lo>
// and is safe to pass to wg show / UAPI because it parses as a valid IP:port.
func WrrpFakeAddrPort(remoteId uint64) netip.AddrPort {
	var b [16]byte
	copy(b[:8], wrrpFakePrefix[:])
	binary.BigEndian.PutUint64(b[8:], remoteId)
	return netip.AddrPortFrom(netip.AddrFrom16(b), WrrpFakePort)
}

// IsWrrpFakeAddr reports whether addr was generated by WrrpFakeAddrPort.
func IsWrrpFakeAddr(addr netip.Addr) bool {
	if !addr.Is6() {
		return false
	}
	b := addr.As16()
	return b[0] == wrrpFakePrefix[0] &&
		b[1] == wrrpFakePrefix[1] &&
		b[2] == wrrpFakePrefix[2] &&
		b[3] == wrrpFakePrefix[3] &&
		b[4] == wrrpFakePrefix[4] &&
		b[5] == wrrpFakePrefix[5]
}

// RemoteIdFromWrrpFakeAddr extracts the RemoteId encoded in a fake WRRP address.
func RemoteIdFromWrrpFakeAddr(addr netip.Addr) uint64 {
	b := addr.As16()
	return binary.BigEndian.Uint64(b[8:])
}

// 1. 自定义一个极简的 Endpoint
type WRRPEndpoint struct {
	// 物理层信息 (用于标准 UDP/ICE)
	Addr netip.AddrPort

	// 协议层信息 (用于 WRRP)
	RemoteId uint64

	// 标志位：当前该走哪条路
	TransportType TransportType
}

func (e *WRRPEndpoint) ClearSrc() {

}

func (e *WRRPEndpoint) Clear() {}
func (e *WRRPEndpoint) DstToString() string {
	// For display purposes (wg show / UAPI GET), always prefer the physical
	// relay address when available.  Routing is driven by DstToBytes() (which
	// uses RemoteId for WRRP) and Send() (which checks TransportType), so
	// returning the relay IP:port here does not affect the data plane.
	if e.Addr.IsValid() {
		return e.Addr.String()
	}
	// Fallback: should not normally be reached because ReceiveFunc always sets
	// Addr to WrrpFakeAddrPort(RemoteId).
	return fmt.Sprintf("wrrp://%d", e.RemoteId)
}

func (e *WRRPEndpoint) DstToBytes() []byte {
	if e.TransportType == WRRP {
		b := make([]byte, 8)
		binary.BigEndian.PutUint64(b, e.RemoteId)
		return b
	}
	// 标准 UDP 模式下，AddrPort 转换为字节
	b, _ := e.Addr.MarshalBinary()
	return b
}

func (e *WRRPEndpoint) DstIP() netip.Addr {
	if e.TransportType == WRRP {
		// WRRP 路由完全由 RemoteId 决定，不走 UDP 路径，
		// 返回 loopback 供 WireGuard 内部速率限制使用。
		return netip.IPv4Unspecified()
	}
	return e.Addr.Addr()
}

func (e *WRRPEndpoint) SrcIP() netip.Addr {
	return netip.Addr{}
}
func (e *WRRPEndpoint) SrcToString() string { return "" }
