---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alattice.io
  resources:
  - latticeclusterpeerings
  - latticeenrollmenttokens
  - latticenetworkpeerings
  - latticenetworks
  - latticepeers
  - latticepolicies
  - latticerelayservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alattice.io
  resources:
  - latticeclusterpeerings/finalizers
  - latticeenrollmenttokens/finalizers
  - latticenetworkpeerings/finalizers
  - latticenetworks/finalizers
  - latticepeers/finalizers
  - latticepolicies/finalizers
  - latticerelayservers/finalizers
  verbs:
  - update
- apiGroups:
  - alattice.io
  resources:
  - latticeclusterpeerings/status
  - latticeenrollmenttokens/status
  - latticenetworkpeerings/status
  - latticenetworks/status
  - latticepeers/status
  - latticepolicies/status
  - latticerelayservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - alattice.io
  resources:
  - latticeclusters
  verbs:
  - get
  - list
  - watch
