---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wireflow-controller-admin
  namespace: wireflow

---
# ClusterRoleBinding - 直接绑定到 cluster-admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wireflow-controller-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # 使用 Kubernetes 内置的 cluster-admin 角色
subjects:
  - kind: ServiceAccount
    name: wireflow-controller-admin
    namespace: wireflow