## Append samples of your project ##
resources:
- latticecontroller_v1alpha1_node.yaml
- latticecontroller_v1alpha1_latticenetwork.yaml
- label1-policy.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
