apiVersion: alattice.io/v1alpha1
kind: LatticePolicy
metadata:
  labels:
    app.kubernetes.io/name: lattice-controller
    app.kubernetes.io/managed-by: kustomize
  name: networkpolicy-sample
spec:
  peerSelector:
    matchLabels:
      app: test
  network: lattice-default-net
  ingressRule:
    - from:
        - peerSelector:
            matchLabels:
              app: test

