// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tc_ingressIpKey struct {
	_      structs.HostLayout
	LpmKey uint32
	SrcIp  uint32
}

type tc_ingressPortKey struct {
	_        structs.HostLayout
	LpmKey   uint32
	SrcIp    uint32
	Protocol uint8
	_        [1]byte
	DstPort  uint16
	Padding  uint8
	_        [3]byte
}

// loadTc_ingress returns the embedded CollectionSpec for tc_ingress.
func loadTc_ingress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tc_ingressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tc_ingress: %w", err)
	}

	return spec, err
}

// loadTc_ingressObjects loads tc_ingress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tc_ingressObjects
//	*tc_ingressPrograms
//	*tc_ingressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTc_ingressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTc_ingress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tc_ingressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_ingressSpecs struct {
	tc_ingressProgramSpecs
	tc_ingressMapSpecs
	tc_ingressVariableSpecs
}

// tc_ingressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_ingressProgramSpecs struct {
	LatticeTcIngress *ebpf.ProgramSpec `ebpf:"lattice_tc_ingress"`
}

// tc_ingressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_ingressMapSpecs struct {
	DefaultActionMap     *ebpf.MapSpec `ebpf:"default_action_map"`
	IngressPolicyMap     *ebpf.MapSpec `ebpf:"ingress_policy_map"`
	IngressPortPolicyMap *ebpf.MapSpec `ebpf:"ingress_port_policy_map"`
}

// tc_ingressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tc_ingressVariableSpecs struct {
}

// tc_ingressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTc_ingressObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_ingressObjects struct {
	tc_ingressPrograms
	tc_ingressMaps
	tc_ingressVariables
}

func (o *tc_ingressObjects) Close() error {
	return _Tc_ingressClose(
		&o.tc_ingressPrograms,
		&o.tc_ingressMaps,
	)
}

// tc_ingressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTc_ingressObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_ingressMaps struct {
	DefaultActionMap     *ebpf.Map `ebpf:"default_action_map"`
	IngressPolicyMap     *ebpf.Map `ebpf:"ingress_policy_map"`
	IngressPortPolicyMap *ebpf.Map `ebpf:"ingress_port_policy_map"`
}

func (m *tc_ingressMaps) Close() error {
	return _Tc_ingressClose(
		m.DefaultActionMap,
		m.IngressPolicyMap,
		m.IngressPortPolicyMap,
	)
}

// tc_ingressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTc_ingressObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_ingressVariables struct {
}

// tc_ingressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTc_ingressObjects or ebpf.CollectionSpec.LoadAndAssign.
type tc_ingressPrograms struct {
	LatticeTcIngress *ebpf.Program `ebpf:"lattice_tc_ingress"`
}

func (p *tc_ingressPrograms) Close() error {
	return _Tc_ingressClose(
		p.LatticeTcIngress,
	)
}

func _Tc_ingressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_ingress_bpfel.o
var _Tc_ingressBytes []byte
