apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6 # 体积最小的官方镜像
          imagePullPolicy: IfNotPresent
          args:
            - "--innodb-flush-log-at-trx-commit=0" # 关键：不立即同步磁盘，性能提升 10 倍
            - "--innodb-doublewrite=0"             # 关键：关闭双写缓存
            - "--skip-innodb-read-only-compressed"
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "root"
            - name: MARIADB_DATABASE
              value: "lattice"
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          emptyDir:
            medium: Memory # 关键：直接将数据存入内存，速度起飞且不占磁盘 IO