name: lint
on: [pull_request, push]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true # 自动缓存依赖，防止超时

      # 解决 undefined: nats 的核心步骤
      - name: Sync Dependencies
        run: |
          go mod tidy
          go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          # 使用配置文件，这里只需要传入超时
          args: --timeout=5m